// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: tenant/tenant.proto

package tenant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plan gates features and quotas per tenant.
type Plan int32

const (
	Plan_PLAN_UNSPECIFIED Plan = 0
	Plan_PLAN_TRIAL       Plan = 1
	Plan_PLAN_PRO         Plan = 2
	Plan_PLAN_ENTERPRISE  Plan = 3
)

// Enum value maps for Plan.
var (
	Plan_name = map[int32]string{
		0: "PLAN_UNSPECIFIED",
		1: "PLAN_TRIAL",
		2: "PLAN_PRO",
		3: "PLAN_ENTERPRISE",
	}
	Plan_value = map[string]int32{
		"PLAN_UNSPECIFIED": 0,
		"PLAN_TRIAL":       1,
		"PLAN_PRO":         2,
		"PLAN_ENTERPRISE":  3,
	}
)

func (x Plan) Enum() *Plan {
	p := new(Plan)
	*p = x
	return p
}

func (x Plan) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Plan) Descriptor() protoreflect.EnumDescriptor {
	return file_tenant_tenant_proto_enumTypes[0].Descriptor()
}

func (Plan) Type() protoreflect.EnumType {
	return &file_tenant_tenant_proto_enumTypes[0]
}

func (x Plan) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Plan.Descriptor instead.
func (Plan) EnumDescriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{0}
}

// Status is the tenant lifecycle state.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_SUSPENDED   Status = 2
	Status_STATUS_DELETED     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_SUSPENDED",
		3: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_SUSPENDED":   2,
		"STATUS_DELETED":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tenant_tenant_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tenant_tenant_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{1}
}

// TenantView is the public read-only shape of a tenant.
//
// SecretKey fingerprint is included on every read; the raw SecretKey
// bytes only ever appear in CreateTenantResp and RotateSecretResp.
type TenantView struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	AppId  uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Plan   Plan                   `protobuf:"varint,3,opt,name=plan,proto3,enum=airchat.tenant.Plan" json:"plan,omitempty"`
	Status Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=airchat.tenant.Status" json:"status,omitempty"`
	// 8-byte hex prefix of SHA-256 over the active SecretKey. Suitable
	// for audit logs and change detection; cannot be used to forge a
	// UserSig.
	SecretKeyFingerprint string `protobuf:"bytes,5,opt,name=secret_key_fingerprint,json=secretKeyFingerprint,proto3" json:"secret_key_fingerprint,omitempty"`
	HasPrevSecret        bool   `protobuf:"varint,6,opt,name=has_prev_secret,json=hasPrevSecret,proto3" json:"has_prev_secret,omitempty"`
	// Unix seconds, or 0 if not applicable.
	PrevExpireAt  int64 `protobuf:"varint,7,opt,name=prev_expire_at,json=prevExpireAt,proto3" json:"prev_expire_at,omitempty"`
	CreatedAt     int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantView) Reset() {
	*x = TenantView{}
	mi := &file_tenant_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantView) ProtoMessage() {}

func (x *TenantView) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantView.ProtoReflect.Descriptor instead.
func (*TenantView) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantView) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TenantView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantView) GetPlan() Plan {
	if x != nil {
		return x.Plan
	}
	return Plan_PLAN_UNSPECIFIED
}

func (x *TenantView) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *TenantView) GetSecretKeyFingerprint() string {
	if x != nil {
		return x.SecretKeyFingerprint
	}
	return ""
}

func (x *TenantView) GetHasPrevSecret() bool {
	if x != nil {
		return x.HasPrevSecret
	}
	return false
}

func (x *TenantView) GetPrevExpireAt() int64 {
	if x != nil {
		return x.PrevExpireAt
	}
	return 0
}

func (x *TenantView) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TenantView) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateTenantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Plan          Plan                   `protobuf:"varint,2,opt,name=plan,proto3,enum=airchat.tenant.Plan" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantReq) Reset() {
	*x = CreateTenantReq{}
	mi := &file_tenant_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantReq) ProtoMessage() {}

func (x *CreateTenantReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantReq.ProtoReflect.Descriptor instead.
func (*CreateTenantReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantReq) GetPlan() Plan {
	if x != nil {
		return x.Plan
	}
	return Plan_PLAN_UNSPECIFIED
}

type CreateTenantResp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tenant *TenantView            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Raw SecretKey bytes. The client MUST store these immediately; the
	// server will never return them again.
	SecretKey     []byte `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResp) Reset() {
	*x = CreateTenantResp{}
	mi := &file_tenant_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResp) ProtoMessage() {}

func (x *CreateTenantResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResp.ProtoReflect.Descriptor instead.
func (*CreateTenantResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantResp) GetTenant() *TenantView {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *CreateTenantResp) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

type GetTenantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantReq) Reset() {
	*x = GetTenantReq{}
	mi := &file_tenant_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantReq) ProtoMessage() {}

func (x *GetTenantReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantReq.ProtoReflect.Descriptor instead.
func (*GetTenantReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type GetTenantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantView            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResp) Reset() {
	*x = GetTenantResp{}
	mi := &file_tenant_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResp) ProtoMessage() {}

func (x *GetTenantResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResp.ProtoReflect.Descriptor instead.
func (*GetTenantResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantResp) GetTenant() *TenantView {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ListTenantsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsReq) Reset() {
	*x = ListTenantsReq{}
	mi := &file_tenant_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsReq) ProtoMessage() {}

func (x *ListTenantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsReq.ProtoReflect.Descriptor instead.
func (*ListTenantsReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{5}
}

type ListTenantsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantView          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResp) Reset() {
	*x = ListTenantsResp{}
	mi := &file_tenant_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResp) ProtoMessage() {}

func (x *ListTenantsResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResp.ProtoReflect.Descriptor instead.
func (*ListTenantsResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *ListTenantsResp) GetTenants() []*TenantView {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type SuspendTenantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantReq) Reset() {
	*x = SuspendTenantReq{}
	mi := &file_tenant_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantReq) ProtoMessage() {}

func (x *SuspendTenantReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantReq.ProtoReflect.Descriptor instead.
func (*SuspendTenantReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *SuspendTenantReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type SuspendTenantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantView            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantResp) Reset() {
	*x = SuspendTenantResp{}
	mi := &file_tenant_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantResp) ProtoMessage() {}

func (x *SuspendTenantResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantResp.ProtoReflect.Descriptor instead.
func (*SuspendTenantResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *SuspendTenantResp) GetTenant() *TenantView {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ResumeTenantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTenantReq) Reset() {
	*x = ResumeTenantReq{}
	mi := &file_tenant_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTenantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTenantReq) ProtoMessage() {}

func (x *ResumeTenantReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTenantReq.ProtoReflect.Descriptor instead.
func (*ResumeTenantReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *ResumeTenantReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type ResumeTenantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantView            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTenantResp) Reset() {
	*x = ResumeTenantResp{}
	mi := &file_tenant_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTenantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTenantResp) ProtoMessage() {}

func (x *ResumeTenantResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTenantResp.ProtoReflect.Descriptor instead.
func (*ResumeTenantResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *ResumeTenantResp) GetTenant() *TenantView {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type DeleteTenantReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantReq) Reset() {
	*x = DeleteTenantReq{}
	mi := &file_tenant_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantReq) ProtoMessage() {}

func (x *DeleteTenantReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantReq.ProtoReflect.Descriptor instead.
func (*DeleteTenantReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTenantReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type DeleteTenantResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResp) Reset() {
	*x = DeleteTenantResp{}
	mi := &file_tenant_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResp) ProtoMessage() {}

func (x *DeleteTenantResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResp.ProtoReflect.Descriptor instead.
func (*DeleteTenantResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{12}
}

type RotateSecretReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretReq) Reset() {
	*x = RotateSecretReq{}
	mi := &file_tenant_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretReq) ProtoMessage() {}

func (x *RotateSecretReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretReq.ProtoReflect.Descriptor instead.
func (*RotateSecretReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *RotateSecretReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

type RotateSecretResp struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tenant *TenantView            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// The NEW SecretKey. The previous one remains valid for
	// RotationGracePeriod (7 days by default) on the server side.
	SecretKey     []byte `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretResp) Reset() {
	*x = RotateSecretResp{}
	mi := &file_tenant_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretResp) ProtoMessage() {}

func (x *RotateSecretResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretResp.ProtoReflect.Descriptor instead.
func (*RotateSecretResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *RotateSecretResp) GetTenant() *TenantView {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *RotateSecretResp) GetSecretKey() []byte {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

type SignUserSigReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	AppId  uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Seconds. If 0 the server applies DefaultUserSigTTL (7 days).
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUserSigReq) Reset() {
	*x = SignUserSigReq{}
	mi := &file_tenant_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUserSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUserSigReq) ProtoMessage() {}

func (x *SignUserSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUserSigReq.ProtoReflect.Descriptor instead.
func (*SignUserSigReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *SignUserSigReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SignUserSigReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignUserSigReq) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SignUserSigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserSig       string                 `protobuf:"bytes,1,opt,name=user_sig,json=userSig,proto3" json:"user_sig,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUserSigResp) Reset() {
	*x = SignUserSigResp{}
	mi := &file_tenant_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUserSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUserSigResp) ProtoMessage() {}

func (x *SignUserSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUserSigResp.ProtoReflect.Descriptor instead.
func (*SignUserSigResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *SignUserSigResp) GetUserSig() string {
	if x != nil {
		return x.UserSig
	}
	return ""
}

func (x *SignUserSigResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type VerifyUserSigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         uint32                 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSig       string                 `protobuf:"bytes,3,opt,name=user_sig,json=userSig,proto3" json:"user_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserSigReq) Reset() {
	*x = VerifyUserSigReq{}
	mi := &file_tenant_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserSigReq) ProtoMessage() {}

func (x *VerifyUserSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserSigReq.ProtoReflect.Descriptor instead.
func (*VerifyUserSigReq) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyUserSigReq) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *VerifyUserSigReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyUserSigReq) GetUserSig() string {
	if x != nil {
		return x.UserSig
	}
	return ""
}

// VerifyUserSigResp. A UserSig-failure (bad signature, expired, wrong
// user) is represented as valid=false rather than a gRPC error — that
// keeps "invalid token" distinct from "tenant not found" or other
// operational faults.
type VerifyUserSigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IssuedAt      int64                  `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"` // Unix seconds; 0 if invalid
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`                     // Seconds of validity; 0 if invalid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserSigResp) Reset() {
	*x = VerifyUserSigResp{}
	mi := &file_tenant_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserSigResp) ProtoMessage() {}

func (x *VerifyUserSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserSigResp.ProtoReflect.Descriptor instead.
func (*VerifyUserSigResp) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *VerifyUserSigResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyUserSigResp) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *VerifyUserSigResp) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

var File_tenant_tenant_proto protoreflect.FileDescriptor

const file_tenant_tenant_proto_rawDesc = "" +
	"\n" +
	"\x13tenant/tenant.proto\x12\x0eairchat.tenant\"\xd3\x02\n" +
	"\n" +
	"TenantView\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x04plan\x18\x03 \x01(\x0e2\x14.airchat.tenant.PlanR\x04plan\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.airchat.tenant.StatusR\x06status\x124\n" +
	"\x16secret_key_fingerprint\x18\x05 \x01(\tR\x14secretKeyFingerprint\x12&\n" +
	"\x0fhas_prev_secret\x18\x06 \x01(\bR\rhasPrevSecret\x12$\n" +
	"\x0eprev_expire_at\x18\a \x01(\x03R\fprevExpireAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"O\n" +
	"\x0fCreateTenantReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04plan\x18\x02 \x01(\x0e2\x14.airchat.tenant.PlanR\x04plan\"e\n" +
	"\x10CreateTenantResp\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.airchat.tenant.TenantViewR\x06tenant\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\fR\tsecretKey\"%\n" +
	"\fGetTenantReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\"C\n" +
	"\rGetTenantResp\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.airchat.tenant.TenantViewR\x06tenant\"\x10\n" +
	"\x0eListTenantsReq\"G\n" +
	"\x0fListTenantsResp\x124\n" +
	"\atenants\x18\x01 \x03(\v2\x1a.airchat.tenant.TenantViewR\atenants\")\n" +
	"\x10SuspendTenantReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\"G\n" +
	"\x11SuspendTenantResp\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.airchat.tenant.TenantViewR\x06tenant\"(\n" +
	"\x0fResumeTenantReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\"F\n" +
	"\x10ResumeTenantResp\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.airchat.tenant.TenantViewR\x06tenant\"(\n" +
	"\x0fDeleteTenantReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\"\x12\n" +
	"\x10DeleteTenantResp\"(\n" +
	"\x0fRotateSecretReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\"e\n" +
	"\x10RotateSecretResp\x122\n" +
	"\x06tenant\x18\x01 \x01(\v2\x1a.airchat.tenant.TenantViewR\x06tenant\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\fR\tsecretKey\"a\n" +
	"\x0eSignUserSigReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"K\n" +
	"\x0fSignUserSigResp\x12\x19\n" +
	"\buser_sig\x18\x01 \x01(\tR\auserSig\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"]\n" +
	"\x10VerifyUserSigReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\rR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sig\x18\x03 \x01(\tR\auserSig\"^\n" +
	"\x11VerifyUserSigResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tissued_at\x18\x02 \x01(\x03R\bissuedAt\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire*O\n" +
	"\x04Plan\x12\x14\n" +
	"\x10PLAN_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PLAN_TRIAL\x10\x01\x12\f\n" +
	"\bPLAN_PRO\x10\x02\x12\x13\n" +
	"\x0fPLAN_ENTERPRISE\x10\x03*]\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x02\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10\x032\xea\x05\n" +
	"\x06Tenant\x12Q\n" +
	"\fCreateTenant\x12\x1f.airchat.tenant.CreateTenantReq\x1a .airchat.tenant.CreateTenantResp\x12H\n" +
	"\tGetTenant\x12\x1c.airchat.tenant.GetTenantReq\x1a\x1d.airchat.tenant.GetTenantResp\x12N\n" +
	"\vListTenants\x12\x1e.airchat.tenant.ListTenantsReq\x1a\x1f.airchat.tenant.ListTenantsResp\x12T\n" +
	"\rSuspendTenant\x12 .airchat.tenant.SuspendTenantReq\x1a!.airchat.tenant.SuspendTenantResp\x12Q\n" +
	"\fResumeTenant\x12\x1f.airchat.tenant.ResumeTenantReq\x1a .airchat.tenant.ResumeTenantResp\x12Q\n" +
	"\fDeleteTenant\x12\x1f.airchat.tenant.DeleteTenantReq\x1a .airchat.tenant.DeleteTenantResp\x12Q\n" +
	"\fRotateSecret\x12\x1f.airchat.tenant.RotateSecretReq\x1a .airchat.tenant.RotateSecretResp\x12N\n" +
	"\vSignUserSig\x12\x1e.airchat.tenant.SignUserSigReq\x1a\x1f.airchat.tenant.SignUserSigResp\x12T\n" +
	"\rVerifyUserSig\x12 .airchat.tenant.VerifyUserSigReq\x1a!.airchat.tenant.VerifyUserSigRespB0Z.github.com/airstarlabs/airchat-protocol/tenantb\x06proto3"

var (
	file_tenant_tenant_proto_rawDescOnce sync.Once
	file_tenant_tenant_proto_rawDescData []byte
)

func file_tenant_tenant_proto_rawDescGZIP() []byte {
	file_tenant_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_tenant_proto_rawDesc), len(file_tenant_tenant_proto_rawDesc)))
	})
	return file_tenant_tenant_proto_rawDescData
}

var file_tenant_tenant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tenant_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_tenant_tenant_proto_goTypes = []any{
	(Plan)(0),                 // 0: airchat.tenant.Plan
	(Status)(0),               // 1: airchat.tenant.Status
	(*TenantView)(nil),        // 2: airchat.tenant.TenantView
	(*CreateTenantReq)(nil),   // 3: airchat.tenant.CreateTenantReq
	(*CreateTenantResp)(nil),  // 4: airchat.tenant.CreateTenantResp
	(*GetTenantReq)(nil),      // 5: airchat.tenant.GetTenantReq
	(*GetTenantResp)(nil),     // 6: airchat.tenant.GetTenantResp
	(*ListTenantsReq)(nil),    // 7: airchat.tenant.ListTenantsReq
	(*ListTenantsResp)(nil),   // 8: airchat.tenant.ListTenantsResp
	(*SuspendTenantReq)(nil),  // 9: airchat.tenant.SuspendTenantReq
	(*SuspendTenantResp)(nil), // 10: airchat.tenant.SuspendTenantResp
	(*ResumeTenantReq)(nil),   // 11: airchat.tenant.ResumeTenantReq
	(*ResumeTenantResp)(nil),  // 12: airchat.tenant.ResumeTenantResp
	(*DeleteTenantReq)(nil),   // 13: airchat.tenant.DeleteTenantReq
	(*DeleteTenantResp)(nil),  // 14: airchat.tenant.DeleteTenantResp
	(*RotateSecretReq)(nil),   // 15: airchat.tenant.RotateSecretReq
	(*RotateSecretResp)(nil),  // 16: airchat.tenant.RotateSecretResp
	(*SignUserSigReq)(nil),    // 17: airchat.tenant.SignUserSigReq
	(*SignUserSigResp)(nil),   // 18: airchat.tenant.SignUserSigResp
	(*VerifyUserSigReq)(nil),  // 19: airchat.tenant.VerifyUserSigReq
	(*VerifyUserSigResp)(nil), // 20: airchat.tenant.VerifyUserSigResp
}
var file_tenant_tenant_proto_depIdxs = []int32{
	0,  // 0: airchat.tenant.TenantView.plan:type_name -> airchat.tenant.Plan
	1,  // 1: airchat.tenant.TenantView.status:type_name -> airchat.tenant.Status
	0,  // 2: airchat.tenant.CreateTenantReq.plan:type_name -> airchat.tenant.Plan
	2,  // 3: airchat.tenant.CreateTenantResp.tenant:type_name -> airchat.tenant.TenantView
	2,  // 4: airchat.tenant.GetTenantResp.tenant:type_name -> airchat.tenant.TenantView
	2,  // 5: airchat.tenant.ListTenantsResp.tenants:type_name -> airchat.tenant.TenantView
	2,  // 6: airchat.tenant.SuspendTenantResp.tenant:type_name -> airchat.tenant.TenantView
	2,  // 7: airchat.tenant.ResumeTenantResp.tenant:type_name -> airchat.tenant.TenantView
	2,  // 8: airchat.tenant.RotateSecretResp.tenant:type_name -> airchat.tenant.TenantView
	3,  // 9: airchat.tenant.Tenant.CreateTenant:input_type -> airchat.tenant.CreateTenantReq
	5,  // 10: airchat.tenant.Tenant.GetTenant:input_type -> airchat.tenant.GetTenantReq
	7,  // 11: airchat.tenant.Tenant.ListTenants:input_type -> airchat.tenant.ListTenantsReq
	9,  // 12: airchat.tenant.Tenant.SuspendTenant:input_type -> airchat.tenant.SuspendTenantReq
	11, // 13: airchat.tenant.Tenant.ResumeTenant:input_type -> airchat.tenant.ResumeTenantReq
	13, // 14: airchat.tenant.Tenant.DeleteTenant:input_type -> airchat.tenant.DeleteTenantReq
	15, // 15: airchat.tenant.Tenant.RotateSecret:input_type -> airchat.tenant.RotateSecretReq
	17, // 16: airchat.tenant.Tenant.SignUserSig:input_type -> airchat.tenant.SignUserSigReq
	19, // 17: airchat.tenant.Tenant.VerifyUserSig:input_type -> airchat.tenant.VerifyUserSigReq
	4,  // 18: airchat.tenant.Tenant.CreateTenant:output_type -> airchat.tenant.CreateTenantResp
	6,  // 19: airchat.tenant.Tenant.GetTenant:output_type -> airchat.tenant.GetTenantResp
	8,  // 20: airchat.tenant.Tenant.ListTenants:output_type -> airchat.tenant.ListTenantsResp
	10, // 21: airchat.tenant.Tenant.SuspendTenant:output_type -> airchat.tenant.SuspendTenantResp
	12, // 22: airchat.tenant.Tenant.ResumeTenant:output_type -> airchat.tenant.ResumeTenantResp
	14, // 23: airchat.tenant.Tenant.DeleteTenant:output_type -> airchat.tenant.DeleteTenantResp
	16, // 24: airchat.tenant.Tenant.RotateSecret:output_type -> airchat.tenant.RotateSecretResp
	18, // 25: airchat.tenant.Tenant.SignUserSig:output_type -> airchat.tenant.SignUserSigResp
	20, // 26: airchat.tenant.Tenant.VerifyUserSig:output_type -> airchat.tenant.VerifyUserSigResp
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tenant_tenant_proto_init() }
func file_tenant_tenant_proto_init() {
	if File_tenant_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_tenant_proto_rawDesc), len(file_tenant_tenant_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_tenant_proto_depIdxs,
		EnumInfos:         file_tenant_tenant_proto_enumTypes,
		MessageInfos:      file_tenant_tenant_proto_msgTypes,
	}.Build()
	File_tenant_tenant_proto = out.File
	file_tenant_tenant_proto_goTypes = nil
	file_tenant_tenant_proto_depIdxs = nil
}
