// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: tenant/tenant.proto

package tenant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tenant_CreateTenant_FullMethodName  = "/airchat.tenant.Tenant/CreateTenant"
	Tenant_GetTenant_FullMethodName     = "/airchat.tenant.Tenant/GetTenant"
	Tenant_ListTenants_FullMethodName   = "/airchat.tenant.Tenant/ListTenants"
	Tenant_SuspendTenant_FullMethodName = "/airchat.tenant.Tenant/SuspendTenant"
	Tenant_ResumeTenant_FullMethodName  = "/airchat.tenant.Tenant/ResumeTenant"
	Tenant_DeleteTenant_FullMethodName  = "/airchat.tenant.Tenant/DeleteTenant"
	Tenant_RotateSecret_FullMethodName  = "/airchat.tenant.Tenant/RotateSecret"
	Tenant_SignUserSig_FullMethodName   = "/airchat.tenant.Tenant/SignUserSig"
	Tenant_VerifyUserSig_FullMethodName = "/airchat.tenant.Tenant/VerifyUserSig"
)

// TenantClient is the client API for Tenant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantReq, opts ...grpc.CallOption) (*CreateTenantResp, error)
	GetTenant(ctx context.Context, in *GetTenantReq, opts ...grpc.CallOption) (*GetTenantResp, error)
	ListTenants(ctx context.Context, in *ListTenantsReq, opts ...grpc.CallOption) (*ListTenantsResp, error)
	SuspendTenant(ctx context.Context, in *SuspendTenantReq, opts ...grpc.CallOption) (*SuspendTenantResp, error)
	ResumeTenant(ctx context.Context, in *ResumeTenantReq, opts ...grpc.CallOption) (*ResumeTenantResp, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantReq, opts ...grpc.CallOption) (*DeleteTenantResp, error)
	RotateSecret(ctx context.Context, in *RotateSecretReq, opts ...grpc.CallOption) (*RotateSecretResp, error)
	SignUserSig(ctx context.Context, in *SignUserSigReq, opts ...grpc.CallOption) (*SignUserSigResp, error)
	VerifyUserSig(ctx context.Context, in *VerifyUserSigReq, opts ...grpc.CallOption) (*VerifyUserSigResp, error)
}

type tenantClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantClient(cc grpc.ClientConnInterface) TenantClient {
	return &tenantClient{cc}
}

func (c *tenantClient) CreateTenant(ctx context.Context, in *CreateTenantReq, opts ...grpc.CallOption) (*CreateTenantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResp)
	err := c.cc.Invoke(ctx, Tenant_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) GetTenant(ctx context.Context, in *GetTenantReq, opts ...grpc.CallOption) (*GetTenantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResp)
	err := c.cc.Invoke(ctx, Tenant_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) ListTenants(ctx context.Context, in *ListTenantsReq, opts ...grpc.CallOption) (*ListTenantsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResp)
	err := c.cc.Invoke(ctx, Tenant_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) SuspendTenant(ctx context.Context, in *SuspendTenantReq, opts ...grpc.CallOption) (*SuspendTenantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendTenantResp)
	err := c.cc.Invoke(ctx, Tenant_SuspendTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) ResumeTenant(ctx context.Context, in *ResumeTenantReq, opts ...grpc.CallOption) (*ResumeTenantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeTenantResp)
	err := c.cc.Invoke(ctx, Tenant_ResumeTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) DeleteTenant(ctx context.Context, in *DeleteTenantReq, opts ...grpc.CallOption) (*DeleteTenantResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantResp)
	err := c.cc.Invoke(ctx, Tenant_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) RotateSecret(ctx context.Context, in *RotateSecretReq, opts ...grpc.CallOption) (*RotateSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResp)
	err := c.cc.Invoke(ctx, Tenant_RotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) SignUserSig(ctx context.Context, in *SignUserSigReq, opts ...grpc.CallOption) (*SignUserSigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignUserSigResp)
	err := c.cc.Invoke(ctx, Tenant_SignUserSig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantClient) VerifyUserSig(ctx context.Context, in *VerifyUserSigReq, opts ...grpc.CallOption) (*VerifyUserSigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUserSigResp)
	err := c.cc.Invoke(ctx, Tenant_VerifyUserSig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServer is the server API for Tenant service.
// All implementations must embed UnimplementedTenantServer
// for forward compatibility.
type TenantServer interface {
	CreateTenant(context.Context, *CreateTenantReq) (*CreateTenantResp, error)
	GetTenant(context.Context, *GetTenantReq) (*GetTenantResp, error)
	ListTenants(context.Context, *ListTenantsReq) (*ListTenantsResp, error)
	SuspendTenant(context.Context, *SuspendTenantReq) (*SuspendTenantResp, error)
	ResumeTenant(context.Context, *ResumeTenantReq) (*ResumeTenantResp, error)
	DeleteTenant(context.Context, *DeleteTenantReq) (*DeleteTenantResp, error)
	RotateSecret(context.Context, *RotateSecretReq) (*RotateSecretResp, error)
	SignUserSig(context.Context, *SignUserSigReq) (*SignUserSigResp, error)
	VerifyUserSig(context.Context, *VerifyUserSigReq) (*VerifyUserSigResp, error)
	mustEmbedUnimplementedTenantServer()
}

// UnimplementedTenantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantServer struct{}

func (UnimplementedTenantServer) CreateTenant(context.Context, *CreateTenantReq) (*CreateTenantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServer) GetTenant(context.Context, *GetTenantReq) (*GetTenantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServer) ListTenants(context.Context, *ListTenantsReq) (*ListTenantsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantServer) SuspendTenant(context.Context, *SuspendTenantReq) (*SuspendTenantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendTenant not implemented")
}
func (UnimplementedTenantServer) ResumeTenant(context.Context, *ResumeTenantReq) (*ResumeTenantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeTenant not implemented")
}
func (UnimplementedTenantServer) DeleteTenant(context.Context, *DeleteTenantReq) (*DeleteTenantResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantServer) RotateSecret(context.Context, *RotateSecretReq) (*RotateSecretResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSecret not implemented")
}
func (UnimplementedTenantServer) SignUserSig(context.Context, *SignUserSigReq) (*SignUserSigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SignUserSig not implemented")
}
func (UnimplementedTenantServer) VerifyUserSig(context.Context, *VerifyUserSigReq) (*VerifyUserSigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyUserSig not implemented")
}
func (UnimplementedTenantServer) mustEmbedUnimplementedTenantServer() {}
func (UnimplementedTenantServer) testEmbeddedByValue()                {}

// UnsafeTenantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServer will
// result in compilation errors.
type UnsafeTenantServer interface {
	mustEmbedUnimplementedTenantServer()
}

func RegisterTenantServer(s grpc.ServiceRegistrar, srv TenantServer) {
	// If the following call panics, it indicates UnimplementedTenantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tenant_ServiceDesc, srv)
}

func _Tenant_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).CreateTenant(ctx, req.(*CreateTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).GetTenant(ctx, req.(*GetTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).ListTenants(ctx, req.(*ListTenantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_SuspendTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).SuspendTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_SuspendTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).SuspendTenant(ctx, req.(*SuspendTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_ResumeTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).ResumeTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_ResumeTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).ResumeTenant(ctx, req.(*ResumeTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).DeleteTenant(ctx, req.(*DeleteTenantReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_RotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).RotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_RotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).RotateSecret(ctx, req.(*RotateSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_SignUserSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUserSigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).SignUserSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_SignUserSig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).SignUserSig(ctx, req.(*SignUserSigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenant_VerifyUserSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserSigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServer).VerifyUserSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenant_VerifyUserSig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServer).VerifyUserSig(ctx, req.(*VerifyUserSigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Tenant_ServiceDesc is the grpc.ServiceDesc for Tenant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tenant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airchat.tenant.Tenant",
	HandlerType: (*TenantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _Tenant_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Tenant_GetTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _Tenant_ListTenants_Handler,
		},
		{
			MethodName: "SuspendTenant",
			Handler:    _Tenant_SuspendTenant_Handler,
		},
		{
			MethodName: "ResumeTenant",
			Handler:    _Tenant_ResumeTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _Tenant_DeleteTenant_Handler,
		},
		{
			MethodName: "RotateSecret",
			Handler:    _Tenant_RotateSecret_Handler,
		},
		{
			MethodName: "SignUserSig",
			Handler:    _Tenant_SignUserSig_Handler,
		},
		{
			MethodName: "VerifyUserSig",
			Handler:    _Tenant_VerifyUserSig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant/tenant.proto",
}
